name: food_delivery_screens_app_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_switch: ^0.3.2
  carousel_slider: ^5.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/images/
    - assets/dark_images/
    - assets/icons/
    - assets/dark_icons/


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 800
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
