name: taxi_booking_driver_app_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  intl: 0.20.2
  country_picker: ^2.0.27
  dotted_line: ^3.2.3
  dotted_border: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  file_picker: ^10.2.0
  fl_chart: 1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#dependency_overrides:
#  intl: ^0.19.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/dark_images/
    - assets/icons/
    - assets/dark_icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
