import 'package:flutter/material.dart';

import '../ui/app/my_app.dart';

class AppAssets {
  static const _path = "packages/goozzy_e_commerce_screens_app_package/";
  static const _pImages = "${_path}assets/images/";
  static const _pDarkImages = "${_path}assets/dark_images/";
  static const _pDarkIcons = "${_path}assets/dark_icons/";
  static const _pIcons = "${_path}assets/icons/";

  static String themeImages =
      (Theme.of(GoozzyECommerceScreensMyApp.navigatorKey.currentContext!).brightness == Brightness.light) ? _pImages : _pDarkImages;
  static String themeIcons =
      (Theme.of(GoozzyECommerceScreensMyApp.navigatorKey.currentContext!).brightness == Brightness.light) ? _pIcons : _pDarkIcons;

  static void refreshAssets() {
    final context = GoozzyECommerceScreensMyApp.navigatorKey.currentContext;
    if (context == null) {
      debugPrint("AppAssets.refreshAssets: context is null.");
      return;
    }
    themeImages = (Theme.of(context).brightness == Brightness.light) ? _pImages : _pDarkImages;
    themeIcons = (Theme.of(context).brightness == Brightness.light) ? _pIcons : _pDarkIcons;
    icFacebook = "${themeIcons}ic_facebook.webp";
    icApple = "${themeIcons}ic_apple.webp";
    icBuy = "${themeIcons}ic_buy.webp";
    icNotification = "${themeIcons}ic_notification.webp";
    icHeart = "${themeIcons}ic_heart.webp";
  }

  /// IMAGES ===================================================================
  static String imgOnBoarding1 = "${_pImages}img_on_boarding1.webp";
  static String imgOnBoarding2 = "${_pImages}img_on_boarding2.webp";
  static String imgOnBoarding3 = "${_pImages}img_on_boarding3.webp";

  static String imgAccountCreated = "${_pImages}img_account_created.webp";
  static String imgSocialLogin = "${_pImages}img_social_login.webp";
  static String imgAppLogo = "${_pImages}img_app_logo.webp";
  static String imgForgotPassword = "${_pImages}img_forgot_password.webp";
  static String imgNewPassword = "${_pImages}img_new_password.webp";
  static String imgCongratulation = "${_pImages}img_congratulation.webp";
  static String imgVerifyCode = "${_pImages}img_verify_code.webp";
  static String imgBanner1 = "${_pImages}img_banner2.webp";
  static String imgBanner2 = "${_pImages}img_banner1.webp";
  static String imgBanner3 = "${_pImages}img_banner3.webp";
  static String imgKurti = "${_pImages}img_kurti.webp";
  static String imgWomenTop = "${_pImages}img_women_top.webp";
  static String imgJumpSuit = "${_pImages}img_jumpsuit.webp";
  static String imgAnniDesigner = "${_pImages}img_anni_designer_saree.webp";
  static String imgWomenArtSilk = "${_pImages}img_women_art_silk.webp";
  static String imgSaree1 = "${_pImages}img_saree1.webp";
  static String imgSaree2 = "${_pImages}img_saree2.webp";
  static String imgSaree3 = "${_pImages}img_saree3.webp";
  static String imgDefault = "${_pImages}img_default.webp";
  static String imgYellowSaree1 = "${_pImages}img_yellow_saree1.webp";
  static String imgYellowSaree2 = "${_pImages}img_yellow_saree2.webp";
  static String imgYellowSaree3 = "${_pImages}img_yellow_saree3.webp";
  static String imgOrangeSaree = "${_pImages}img_orange_saree.webp";
  static String imgOrangeSaree1 = "${_pImages}img_orange_saree1.webp";
  static String imgOrangeSaree2 = "${_pImages}img_orange_saree2.webp";
  static String imgOrangeSaree3 = "${_pImages}img_orange_saree3.webp";
  static String imgOrangeSaree4 = "${_pImages}img_orange_saree4.webp";
  static String imgOrangeSaree5 = "${_pImages}img_orange_saree5.webp";
  static String imgOrangeSaree6 = "${_pImages}img_orange_saree6.webp";
  static String imgWinter = "${_pImages}img_winter.webp";
  static String imgWatch = "${_pImages}img_watch.webp";
  static String imgTShirt = "${_pImages}img_tshirt.webp";
  static String imgTrackSuit = "${_pImages}img_tracksuit.webp";
  static String imgTopWear = "${_pImages}img_topwear.webp";
  static String imgSweater = "${_pImages}img_sweater.webp";
  static String imgShirt = "${_pImages}img_shirt.webp";
  static String imgLeatherBelt = "${_pImages}img_leather_belt.webp";
  static String imgJeans = "${_pImages}img_jeans.webp";
  static String imgJacket = "${_pImages}img_jacket.webp";
  static String imgAccessories = "${_pImages}img_accessories.webp";
  static String imgTrousers = "${_pImages}img_trouser.webp";
  static String imgSummerSale = "${_pImages}img_summer_sale.webp";
  static String imgDennisShirt = "${_pImages}img_dennis_shirt.webp";
  static String imgDennisShirt2 = "${_pImages}img_dennis_shirt2.webp";
  static String imgShirt1 = "${_pImages}img_shirt1.webp";
  static String imgShirt2 = "${_pImages}img_shirt2.webp";
  static String imgShirt3 = "${_pImages}img_shirt3.webp";
  static String imgShirt4 = "${_pImages}img_shirt4.webp";
  static String imgNoPost = "${_pImages}img_no_post.webp";
  static String imgWishlist = "${_pImages}img_wishlist.webp";
  static String imgShared = "${_pImages}img_shared.webp";
  static String imgLevelZero = "${_pImages}img_level_zero.webp";
  static String imgLevelOne = "${_pImages}img_level_one.webp";
  static String imgRefer = "${_pImages}img_refer.webp";
  static String imgEarnMore = "${_pImages}img_earn_more.webp";
  static String imgMoney = "${_pImages}img_money.webp";
  static String imgPaytm = "${_pImages}img_paytm.webp";
  static String imgCreditCard = "${_pImages}img_credit_card.webp";
  static String imgDeliveryMan = "${_pImages}img_delivery_man.webp";
  static String imgPaymentFailed = "${_pImages}img_payment_failed.webp";
  static String imgOrderSuccessfully = "${_pImages}img_order_successfully.webp";
  static String imgOrderCancelled = "${_pImages}img_order_cancelled.webp";
  static String imgEmptyOrder = "${_pImages}img_empty_order.webp";
  static String imgEmptyNotification = "${_pImages}img_empty_notification.webp";
  static String imgNotification1 = "${_pImages}img_notification1.webp";
  static String imgNotification2 = "${_pImages}img_notification2.webp";
  static String imgNotification3 = "${_pImages}img_notification3.webp";
  static String imgNotification4 = "${_pImages}img_notification4.webp";
  static String imgNotification5 = "${_pImages}img_notification5.webp";
  static String imgNotification6 = "${_pImages}img_notification6.webp";
  static String imgEmptySearch = "${_pImages}img_empty_search.webp";
  static String imgBgHomeScreenPlain = "${_pImages}img_bg_home_screen_plain.webp";
  static String imgSplash = "${_pImages}img_splash.webp";

  static String icLeftArrow = "${_pIcons}ic_left_arrow.webp";
  static String icFacebook = "${themeIcons}ic_facebook.webp";
  static String icGoogle = "${_pIcons}ic_google.webp";
  static String icApple = "${themeIcons}ic_apple.webp";
  static String icProfile = "${_pIcons}ic_profile.webp";
  static String icCloseSquare = "${_pIcons}ic_close_square.webp";
  static String icMail = "${_pIcons}ic_mail.webp";
  static String icPassword = "${_pIcons}ic_password.webp";
  static String icAvatar = "${_pIcons}ic_avatar.webp";
  static String icBag = "${_pIcons}ic_bag.webp";
  static String icBuy = "${_pIcons}ic_buy.webp";
  static String icCategory = "${_pIcons}ic_category.webp";
  static String icCoat = "${_pIcons}ic_coat.webp";
  static String icDownArrow = "${_pIcons}ic_down_arrow.webp";
  static String icUpFilter = "${_pIcons}ic_up_filter.webp";
  static String icDownFilter = "${_pIcons}ic_down_filter.webp";
  static String icDress = "${_pIcons}ic_dress.webp";
  static String icFilter = "${_pIcons}ic_filter.webp";
  static String icFootwear = "${_pIcons}ic_footwear.webp";
  static String icHeart = "${_pIcons}ic_heart.webp";
  static String icHome = "${_pIcons}ic_home.webp";
  static String icKids = "${_pIcons}ic_kids.webp";
  static String icNotification = "${_pIcons}ic_notification.webp";
  static String icSearch = "${_pIcons}ic_search.webp";
  static String icStar = "${_pIcons}ic_star.webp";
  static String icVoice = "${_pIcons}ic_voice.webp";
  static String icWhatsapp = "${_pIcons}ic_whatsapp.webp";
  static String icDiscount = "${_pIcons}ic_discount.webp";
  static String icLeft = "${_pIcons}ic_left.webp";
  static String icCopy = "${_pIcons}ic_copy.webp";
  static String icTrust = "${_pIcons}ic_trust.webp";
  static String icCod = "${_pIcons}ic_cash_on_delivery.webp";
  static String icReturn = "${_pIcons}ic_return.webp";
  static String icPriceTag = "${_pIcons}ic_price_tag.webp";
  static String icLike = "${_pIcons}ic_like.webp";
  static String icArrowFilter = "${_pIcons}ic_arrow_filter.webp";
  static String icCalender = "${_pIcons}ic_calender.webp";
  static String icLabel = "${_pIcons}ic_label.webp";
  static String icShare = "${_pIcons}ic_share.webp";
  static String icShipping = "${_pIcons}ic_shipping.webp";
  static String icMen = "${_pIcons}ic_men.webp";
  static String icWomen = "${_pIcons}ic_women.webp";
  static String icGirl = "${_pIcons}ic_girl.webp";
  static String icBoy = "${_pIcons}ic_boy.webp";
  static String icPercentage = "${_pIcons}ic_percentage.webp";
  static String icDownload = "${_pIcons}ic_download.webp";
  static String icSpins = "${_pIcons}ic_spins.webp";
  static String icSetting = "${_pIcons}ic_setting.webp";
  static String icRate = "${_pIcons}ic_rate.webp";
  static String icPayment = "${_pIcons}ic_payment.webp";
  static String icNotificationBell = "${_pIcons}ic_notification_bell.webp";
  static String icMore = "${_pIcons}ic_more.webp";
  static String icLogo = "${_pIcons}ic_logo.webp";
  static String icChallenge = "${_pIcons}ic_challenges.webp";
  static String icAccountBalance = "${_pIcons}ic_account_balance.webp";
  static String icBank = "${_pIcons}ic_bank.webp";
  static String icRefer = "${_pIcons}ic_refer.webp";
  static String icRightArrow = "${_pIcons}ic_right_arrow.webp";
  static String icEditProfile = "${_pIcons}ic_edit_profile.webp";
  static String icAdd = "${_pIcons}ic_add.webp";
  static String icCamera = "${_pIcons}ic_camera.webp";
  static String icFilledFavourite = "${_pIcons}ic_filled_heart.webp";
  static String icGreyDiscount = "${_pIcons}ic_grey_discount.webp";
  static String icYoutubePlay = "${_pIcons}ic_youtube_play.webp";
  static String icCheck = "${_pIcons}ic_check.webp";
  static String icNotCheck = "${_pIcons}ic_not_check.webp";
  static String icPlus = "${_pIcons}ic_plus.webp";
  static String icMinus = "${_pIcons}ic_minus.webp";
  static String icEstimateDate = "${_pIcons}ic_estimate_date.webp";
  static String icOrderConfirmed = "${_pIcons}ic_check.webp";
  static String icOrderCancelled = "${_pIcons}ic_cancelled.webp";
  static String icOrderProcessing = "${_pIcons}ic_processing.webp";
  static String icOrderDelivered = "${_pIcons}ic_delivered.webp";
  static String icOrderPending = "${_pIcons}ic_pending.webp";
  static String icOrderDispatch = "${_pIcons}ic_dispatch.webp";
  static String icGreyStar = "${_pIcons}ic_grey_star.webp";
  static String icHide = "${_pIcons}ic_hide.webp";
  static String icLogout = "${_pIcons}ic_logout.webp";
  static String icHistory = "${_pIcons}ic_history.webp";
  static String icScreens = "${_pIcons}ic_screen.webp";
}
