import 'package:cinemix_app/utils/app_assets.dart';

class Movie {
  final String title;
  final String image;
  final String year;
  final String category;
  final String subCategory;
  final List<String> languages;
  final double? rank;
  final List<String> genres;
  final String description;
  final List<Cast> cast;
  final String? watchTime;
  final String? totalTime;
  final bool isTop10;
  bool isAddedInMyList;

  Movie({
    required this.title,
    required this.image,
    this.year = "2020",
    this.languages = const ["English", "Korean"],
    this.rank,
    this.category = "",
    this.subCategory = "",
    this.genres = const ["Biopic", "Action", "Historical"],
    this.description = "",
    List<Cast>? cast,
    this.watchTime = "",
    this.isTop10 = false,
    this.totalTime = "",
    this.isAddedInMyList = false,
  }) : cast = cast ??
            [
              Cast(
                name: "Chris Hemsworth",
                image: AppAssets.imgChris,
              ),
              Cast(
                name: "Chris Hemsworth",
                image: AppAssets.imgChris,
              ),
              Cast(
                name: "Chris Hemsworth",
                image: AppAssets.imgChris,
              ),
              Cast(
                name: "Chris Hemsworth",
                image: AppAssets.imgChris,
              ),
              Cast(
                name: "Chris Hemsworth",
                image: AppAssets.imgChris,
              ),
            ];
}

class Cast {
  final String name;
  final String image;

  Cast({this.name = '', this.image = ''});
}

class LanguagesList {
  final String language;
  final String languageImage;

  LanguagesList({required this.language, required this.languageImage});
}

final List<Movie> movies = [
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted4,
    category: "Featured",
    subCategory: "Movie",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted2,
    category: "Featured",
    subCategory: "Movie",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted3,
    category: "Featured",
    subCategory: "Movie",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted1,
    category: "Featured",
    subCategory: "Series",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted2,
    category: "Featured",
    subCategory: "Series",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted3,
    category: "Featured",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted5,
    category: "Featured",
    subCategory: "Tv",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgDummySport,
    category: "Featured",
    subCategory: "Sport",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted6,
    category: "Featured",
    subCategory: "Tv",
    rank: 9.8,
  ),
  Movie(
    title: "Chhlaawa",
    image: AppAssets.imgGetStarted7,
    category: "Featured",
    subCategory: "Tv",
    rank: 9.8,
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgInterest7,
    category: "Continue Watching",
    watchTime: "1h 45min",
    totalTime: "2h 00mim",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgInterest5,
    category: "Continue Watching",
    watchTime: "2h 40min",
    totalTime: "3h 00mim",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgInterest3,
    category: "Continue Watching",
    watchTime: "1h 20min",
    totalTime: "3h 00mim",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgInterest4,
    category: "Continue Watching",
    watchTime: "1h 5min",
    totalTime: "3h 00mim",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgInterest1,
    category: "Continue Watching",
    watchTime: "1h 55min",
    rank: 9.8,
    totalTime: "2h 00mim",
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgInterest6,
    category: "Continue Watching",
    watchTime: "20min",
    totalTime: "1h 00mim",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Chhorii",
    image: AppAssets.imgGetStarted1,
    category: "Top 10",
    isTop10: true,
    rank: 1,
    subCategory: "Movie",
  ),
  Movie(
    title: "Superman",
    image: AppAssets.imgGetStarted2,
    category: "Top 10",
    isTop10: true,
    rank: 2,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted3,
    category: "Top 10",
    isTop10: true,
    rank: 3,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted4,
    category: "Top 10",
    isTop10: true,
    rank: 4,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted5,
    category: "Top 10",
    isTop10: true,
    rank: 5,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted6,
    category: "Top 10",
    isTop10: true,
    rank: 6,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted7,
    category: "Top 10",
    isTop10: true,
    rank: 7,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted8,
    category: "Top 10",
    isTop10: true,
    rank: 8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "Top 10",
    isTop10: true,
    rank: 9,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted1,
    category: "Top 10",
    isTop10: true,
    rank: 10,
    subCategory: "Movie",
  ),
  Movie(
    title: "Superman",
    image: AppAssets.imgGetStarted4,
    rank: 9.8,
    category: "Action Movies",
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted3,
    category: "Action Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted5,
    category: "Action Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "Action Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted1,
    category: "Action Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted3,
    category: "For Anime Fans",
    rank: 9.8,
    subCategory: "Series",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted2,
    category: "For Anime Fans",
    rank: 9.8,
    subCategory: "Series",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "For Anime Fans",
    rank: 9.8,
    subCategory: "Series",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted7,
    category: "For Anime Fans",
    rank: 9.8,
    subCategory: "Series",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgDummySport,
    category: "Non-Stop Sport",
    rank: 9.8,
    subCategory: "Sport",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgDummySport,
    category: "Non-Stop Sport",
    rank: 9.8,
    subCategory: "Sport",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgDummySport,
    category: "Non-Stop Sport",
    rank: 9.8,
    subCategory: "Sport",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgDummySport,
    category: "Non-Stop Sport",
    rank: 9.8,
    subCategory: "Sport",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted3,
    category: "Best In Comedy",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted1,
    category: "Best In Comedy",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "Best In Comedy",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted3,
    category: "Best In Comedy",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted7,
    category: "Superhit Biopic",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted2,
    category: "Superhit Biopic",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "Superhit Biopic",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted3,
    category: "Superhit Biopic",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted6,
    category: "Movies From The 2010s",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted8,
    category: "Movies From The 2010s",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted1,
    category: "Movies From The 2010s",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted2,
    category: "Movies From The 2010s",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted7,
    category: "Popular Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted4,
    category: "Popular Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "Popular Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted2,
    category: "Popular Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted7,
    category: "Popular Movies",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted4,
    category: "Popular Show",
    rank: 9.8,
    subCategory: "Tv",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "Popular Show",
    rank: 9.8,
    subCategory: "Tv",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted2,
    category: "Popular Show",
    rank: 9.8,
    subCategory: "Tv",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted3,
    category: "New Release",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted7,
    category: "New Release",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted9,
    category: "New Release",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted1,
    category: "New Release",
    rank: 9.8,
    subCategory: "Show",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted2,
    category: "New Release",
    rank: 9.8,
    subCategory: "Series",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted3,
    category: "New Release",
    rank: 9.8,
    subCategory: "Anime",
  ),
  Movie(
    title: "Miroo",
    image: AppAssets.imgGetStarted8,
    category: "New Release",
    rank: 9.8,
    subCategory: "Show",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted4,
    category: "New Release",
    rank: 9.8,
    subCategory: "Movie",
  ),
  Movie(
    title: "XO Kitty",
    image: AppAssets.imgGetStarted2,
    category: "New Release",
    rank: 9.8,
    subCategory: "Drama",
  ),
];
