name: stoxy_app_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  percent_indicator: ^4.2.4
  flutter_slidable: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_switch: ^0.3.2
  intl_phone_field: ^3.2.0
  intl: 0.20.2
  animated_bottom_navigation_bar: ^1.4.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  country_code_picker: ^3.3.0
  model_viewer_plus: ^1.8.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.1.1
  fl_chart: ^1.0.0
  interactive_chart: ^0.3.6
  syncfusion_flutter_gauges: ^29.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#dependency_overrides:
#  intl: ^0.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/dark_images/
    - assets/icons/
    - assets/dark_icons/

  fonts:
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf  
          weight: 400
        - asset: assets/fonts/AvenirNextLTPro-Demi.otf
          weight: 600
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 700
    - family: AvenirLTPro
      fonts:
        - asset: assets/fonts/AvenirLTPro-Medium.otf
          weight: 500



  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
